Repository testit-tms/importers, pull requests merged in 2022-10, with the labels that each got.

#14 Added Junit report importer
  testit-importer-junit/README.md
  testit-importer-junit/connection_config.ini
  testit-importer-junit/main.py
  testit-importer-junit/setup.py
  testit-importer-junit/src/__init__.py
  testit-importer-junit/src/__main__.py
  testit-importer-junit/src/apiclient.py
  testit-importer-junit/src/configurator.py
  testit-importer-junit/src/importer.py
  testit-importer-junit/src/parser.py
  testit-importer-junit/src/status.py
  testit-importer-junit/src/testcase.py
Labels: enhancement

#16 Fixed dependencies.
  testit-importer-allure/setup.py
  testit-importer-allure/src/__main__.py
Labels: bug

#17 Refactor
  .flake8
  .github/release-drafter.yml
  .github/workflows/code_checks.yml
  .github/workflows/release-draft.yml
  testit-importer-allure/.gitignore
  testit-importer-allure/.pylintrc
  testit-importer-allure/.run/Debug.run.xml
  testit-importer-allure/connection_config.ini
  testit-importer-allure/debug.py
  testit-importer-allure/requirements.txt
  testit-importer-allure/setup.py
  testit-importer-allure/src/__main__.py
  testit-importer-allure/src/apiclient.py
  testit-importer-allure/src/configurator.py
  testit-importer-allure/src/filedto.py
  testit-importer-allure/src/filereader.py
  testit-importer-allure/src/importer.py
  testit-importer-allure/src/minioreader.py
  testit-importer-allure/src/parser.py
  testit-importer-allure/src/rabbitmq.py
  testit-importer-allure/src/reader.py
  testit-importer-allure/src/utils.py
Labels: bug, enhancement

#18 Fixed labels
  testit-importer-allure/setup.py
  testit-importer-allure/src/importer.py
Labels: enhancement

#19 Updated documentations
  README.md
  testit-importer-allure/README.md
Labels: documentation
