Repository testit-tms/importers, pull requests merged in 2022-11, with the labels that each got.

#20 Increased version
  testit-importer-allure/setup.py
  testit-importer-junit/setup.py
Labels: documentation

#22 Feature/update client version
  testit-importer-allure/connection_config.ini
  testit-importer-allure/setup.py
  testit-importer-allure/src/apiclient.py
  testit-importer-allure/src/converter.py
  testit-importer-allure/src/importer.py
  testit-importer-junit/setup.py
  testit-importer-junit/src/apiclient.py
  testit-importer-junit/src/converter.py
  testit-importer-junit/src/importer.py
Labels: bug, enhancement

#23 Fixed URL check.
  testit-importer-allure/setup.py
  testit-importer-allure/src/configurator.py
  testit-importer-junit/setup.py
  testit-importer-junit/src/configurator.py
Labels: bug
