Repository testit-tms/importers, pull requests merged in 2023-12, with the labels that each got.

#52 Added a metric to the documentation.
  testit-importer-allure/README.md
Labels: documentation

#51 Fixed getting the link type.
  testit-importer-allure/setup.py
  testit-importer-allure/src/importer.py
Labels: bug

#53 Updated workflow
  .github/workflows/code_checks.yml
Labels: enhancement

#54 Fixed nullable parameters in steps.
  testit-importer-allure/setup.py
  testit-importer-allure/src/importer.py
  testit-importer-allure/src/parser.py
Labels: bug
